name: Publish Package
on:
  push:
    branches:
      - main
      - master
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Login And Set The Scope
        run: |
          npm i -g npm-cli-login
          npm-cli-login --scope=@vitrin-app --username=${GITHUB_ACTOR} --password=${GITHUB_TOKEN}


      - name: Install Dependencies
        run: npm ci

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
